language: node_js
node_js:
  - node
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run build
  - npm run lint-nofix
  - npm run test
  - npm run docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  target_branch: docs
  local_dir: docs
  on:
    branch: master
env:
  global:
    secure: Q0f0CuoMedWzvOq6wkJUwQ/aeb6ES0yLHYKhfdYpIpc11e18OoyKRhGQPyAXciPohz3MsefKi+b+0VmcXK1Xan1RqxzzeHtWhYzpcJNsjhl0n1fhKRtjfVToe38PzC8YBcgUfxxqqkmq4MqzIjpcLax7lz2LuNDHqKxg7ZUCe8jW82T5RKCPon6YInkqiHn4FtQYHJrXWMs59U7iqQ0SnDch4zJUld6HJhH6o+qHW9qaIWbFzzDvZyYiyvTB1evSlRr6WzX9GXiFaccvXEiye3o1bV4JDK0jI3iGJnipPEg9I/2k+2FTWS6eQSNVNyGVuJ8iKncJOWdeIsr7C2kaQXRxDvvAOOL3vYKeR0t/jzxp5xPye7RkJgy/XFMJnAO2IxvrIjX7Y1z5SAteOKAbPd2QBvT+MxAVELMLa1I9v7t43ssjKp6rfkr5NbgI7ERcWBxzPuVLne8cQqVzwqLgpujW0omBdImD0LqbG3Nn9TgHxSrrac6i8OLJBI2+alypfXqIt1TfSQQSVQdaENa8LZMVPuIHM9k66KL5hWadGQi/WyzoSEa0DyfTeUhIVkLDYh+3X8UqwKp+AtwWc2qL91q6NrwuYR8L1JBLSywVUnf9lrsBAHHcmUZ/6EQgbQKIq8D6/zyuxDhFEoZZzE6xgFVhqLRu135cTtngL7ktzbI=
